name: GitHub Pages Preview
on:
  push:
    branches:
      - main
  pull_request: # PR作成時にプレビューを動かす
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write # PRにコメントを残すために必須
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 本番（main）への反映
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploying to Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4

      # プレビュー（Pull Request）の作成
      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
